services:
  davex:
    image: ghcr.io/qooode/nzbdavex:stable
    container_name: davex
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:3000/health || exit 1
      interval: 1m
      retries: 3
      start_period: 5s
      timeout: 5s
    ports:
      - "3000:3000"
    environment:
      - PUID=1000 # (edit these if necessary)
      - PGID=1000
    volumes:
      - ./davex/config:/config
      - ./downloads:/data/downloads # this is where the NZB files are temporarily stored after being downloaded as .strm files, which are promptly renamed and moved to the media folder.
      - /mnt:/mnt
      - ./media:/data/media # the directory of your actual media which will be used by Jellyfin

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000 # (edit these if necessary)
      - PGID=1000
    ports:
      - "8989:8989"
    volumes:
      - ./sonarr/config:/config
      - ./downloads:/data/downloads
      - ./media:/data/media
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000 # (edit these if necessary)
      - PGID=1000
    ports:
      - "7878:7878"
    volumes:
      - ./radarr/config:/config
      - ./downloads:/data/downloads
      - ./media:/data/media

Seerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: Seerr
    init: true
    restart: unless-stopped
    environment:
      - AUTH_COOKIE_SAMESITE=None
      - AUTH_COOKIE_SECURE=true
    ports:
      - "5055:5055"
    volumes:
      - ./Seerr/config:/app/config

jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel # optional: this enables intel quicksync passthrough
    ports:
      - "8096:8096"
    devices:
      - /dev/dri:/dev/dri # Intel QuickSync Passthrough
    volumes:
      - ./usenet/media:/usenet-media:ro
      - ./jellyfin/config:/config
